### ISSUE TITLE
Support baseline in PHP format

### ISSUE THREAD

**Issue by stof** [staabm/phpstan-baseline-analysis#111]
phpstan now supports baselines written in PHP format (to avoid the need for parsing neon, which helps with huge baselines). It would be great to be able to analyze them as well.

**Comment by staabm** [comment]
I don't plan to work on adding support for them, as we don't need them for our particular use-cases.

I am open for contributions though

**Comment by staabm** [comment]
Implemented https://github.com/staabm/phpstan-baseline-analysis/pull/112
